services:
  java-app:
    build: ./backend
    container_name: java-app
    volumes:
      - ./backend:/app:rw
      - ./backend/target:/app/target:rw
    working_dir: /app
    command: ["java", "-jar", "target/gestion-documentos-0.0.1-SNAPSHOT.jar"]
    networks:
      - app-network
    depends_on:
      elasticsearch:
        condition: service_healthy
      python-wrapper:
        condition: service_started
      mysql-db:
        condition: service_healthy

  python-wrapper:
    build: ./wrapper
    container_name: python-wrapper
    volumes:
      - ./wrapper:/app:rw
    working_dir: /app
    command: ["python", "wrapper.py"]
    networks:
      - app-network
    depends_on:
      elasticsearch:
        condition: service_healthy

  mysql-db:
    image: mysql:8.0.33
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: miapp
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/db-mysql/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5
      start_period: 10s

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail http://localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      retries: 5
      start_period: 10s

networks:
  app-network:
    driver: bridge

volumes:
  elastic_data:
  mysql_data:
