services:
  mysql:
    image: mysql:8.0.33
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: miapp
    ports:
      - "3306:3306"
    volumes:
      - ./schema:/var/lib/mysql